import json
import random
from channels.generic.websocket import WebsocketConsumer

# BANQUE DE DONNÉES GÉANTE - Classée par catégorie et par type
BANQUE_QUESTIONS = {
    "amical": {
        "action": [
            "Fais une déclaration d'amour d'une minute à un objet random dans la pièce.",
            "Imite un animal de la ferme jusqu'à ce que quelqu'un devine lequel c'est.",
            "Laisse le groupe envoyer un message drôle à l'un de tes contacts au hasard.",
            "Parle avec un accent étranger pendant les 3 prochains tours.",
            "Fais 15 pompes ou 20 squats tout de suite !",
            "Essaie de toucher ton nez avec ta langue.",
            "Danse sans musique pendant 30 secondes au milieu de la pièce.",
            "Montre ta pire photo de profil d'enfance au groupe.",
            "Échange tes chaussures avec la personne à ta gauche pour les 2 prochains tours.",
            "Fais une imitation parfaite d'un professeur ou d'un patron connu."
        ],
        "verite": [
            "Quelle est la chose la plus ridicule que tu as faite par pure flemme ?",
            "Quel est ton pire tue-l'amour chez quelqu'un ?",
            "As-tu déjà menti pour éviter de sortir avec tes amis ici présents ?",
            "Quelle est la plus grosse bêtise que tu as faite à l'école ?",
            "Si tu devais changer une seule chose chez ton meilleur ami, ce serait quoi ?",
            "Quel est le pire cadeau que tu as jamais reçu ?",
            "Quelle est ta plus grande peur totalement irrationnelle ?",
            "Quelle est la dernière célébrité sur laquelle tu as fantasmé ?",
            "As-tu déjà fait semblant d'être malade pour échapper à un rendez-vous ?",
            "Quel est le pire plat que tu as cuisiné et fait avaler à quelqu'un ?"
        ]
    },
    "amoureux": {
        "action": [
            "Fais un massage des mains de 2 minutes à ton/ta partenaire ou ton crush.",
            "Regarde ton crush/partenaire dans les yeux pendant 30 secondes sans rigoler.",
            "Écris un poème de 4 lignes ultra romantique et lis-le à haute voix.",
            "Chante le refrain d'une chanson d'amour légendaire en fixant quelqu'un ici.",
            "Cite 3 choses que tu adores physiquement chez la personne en face de toi.",
            "Donne un surnom mignon à ton/ta partenaire pour le reste de la soirée.",
            "Fais un compliment poussé et sincère à la personne qui te plaît le plus ici.",
            "Rejoue la scène de ta demande ou de ta rencontre en version totalement exagérée.",
            "Envoie un message 'Je pense à toi' sans explication à ton ex ou ton crush actuel.",
            "Danse un slow de 30 secondes avec la personne de ton choix."
            "Échangeons nos tenues !",
            "Utilise tes pires phrases d'accroche sur moi pendant une minute.",
            "Laisse-moi te dessiner un tatouage au marqueur permanent. (Remarque : choisissez un endroit discret !)",
            "Fais un croquis de ton meilleur portrait de moi.",
            "Fais ta meilleure imitation de moi.",
            "Laisse-moi publier une photo de mon choix dans ta story Instagram.",
            "Mange une cuillerée de n'importe quel condiment dans le réfrigérateur.",
            "Parle avec un accent pendant le reste de la soirée.",
            "Fais de ton mieux pour imiter une célébrité.",
            "Laisse-moi te maquiller ou coiffer tes cheveux.",
            "Fais une capture d'écran de l'historique de ton navigateur et envoie-la par SMS à notre groupe de discussion familial.",
            "Prends un selfie ridicule avec moi et mets-le en photo de profil.",
            "Laisse-moi envoyer tout ce que je veux par SMS à ton meilleur ami.",
            "Prends une douche habillé.e.",
            "Porte une tenue de mon choix pour le reste du jeu.",
            "Mets un bandeau sur tes yeux et laisse-moi te donner à manger quelque chose du réfrigérateur.",
            "Mets un glaçon dans tes sous-vêtements.",
            "Fais-moi une demande en mariage, en plaisantant, de la manière la plus dramatique possible.",
            "Fais-moi un massage de 10 minutes.",
            "Mets une chanson qui te fait penser à moi.",
            "Chante-moi une sérénade avec une chanson de ton choix.",
            "Écris-moi une chanson d'amour ou un poème en crayons ou moins.",
            "Maintiens le contact visuel avec moi pendant deux minutes.",
            "Dessine un portrait de notre premier rendez-vous.",
            "Dis-moi quelque chose que tu n'as jamais dit à personne auparavant.",
            "Donne-moi un surnom mignon mais ridicule.",
            "Fais-moi une déclaration d'amour improvisée.",
            "Cite 3 de mes meilleures qualités sans réfléchir.",
            "Murmure moi des mots doux dans l'oreille sans rigoler.",
            "57. Embrasse la partie que tu préfères de mon corps.",
            "Choisis un extrait d'un livre érotique et lis-le à voix haute.",
            "Enlève un de mes vêtements en utilisant uniquement ta bouche.",
            "Mets une chanson sur laquelle tu aimerais avoir des relations sexuelles.",
            "Fais semblant d'avoir un orgasme.",
            "Décris-moi comment tu te masturbes ou ce que tu ressens lors d'un orgasme.",
            "Épelle l'alphabet avec ta langue posée quelque part sur mon corps.",
            "Va dans la salle de bain ou dans la chambre et envoie-moi un selfie sexy.",
            "Chuchote-moi des mots cochons à l'oreille.",
            "Fais-moi une lap dance.",
            "Fais la tâche que j'aime le moins faire mais en étant nu.e.",
            "Dessine-moi nu.e.",
            "Mange un fruit de la manière la plus sexy possible.",
            "Porte un bandeau sur les yeux lors de nos prochains ébats sexuels.",
            "Trouve un sextoy en ligne que tu aimerais essayer avec moi.",
            "Prépare-moi un en-cas en ne portant qu'un tablier.",
            "Embrasse-moi profondément pendant cinq minutes.",
            "Fais-moi un massage passionnant durant 5 minutes.",
        ],
        "verite": [
            "Quel a été ton premier avis sur moi quand on s'est rencontrés ?",
            "Où s'est passé ton pire rendez-vous amoureux et pourquoi ?",
            "Quel est le geste le plus romantique que l'on ait fait pour toi ?",
            "As-tu déjà eu un coup de foudre au premier regard ?",
            "Quelle est la qualité que tu recherches absolument chez un partenaire ?",
            "Quel est ton souvenir préféré de notre relation / de notre rencontre ?",
            "As-tu déjà fouillé les réseaux sociaux d'un(e) ex très tard le soir ?",
            "Quelle est la plus longue période passée sans donner de nouvelles à quelqu'un qui te plaisait ?",
            "As-tu déjà rompu par simple message textuel ?",
            "À quel âge as-tu eu ton tout premier bisou et c'était comment ?"
            "Quelle partie de mon corps preferes-tu ?",
            "Quand et ou a eu lieu ta premiere dois ?",
            "Definis moi en un mot",
            "Quel est ton « red flag » (signal d'alarme) le plus inattendu ?",
            " Quelle est la seule chose que tu fais seulement quand tu es seul.e ?",
            "Quelle est la seule chose que tu aimerais que les gens/je sache.nt sur toi ?",
            "Quel crime commettrais-tu si tu sais que tu ne te feras jamais prendre ?",
            "Quel est ton plus grand regret ?",
            "Quel a été le plus beau jour de ta vie ?",
            "Quel a été le pire jour de ta vie ?",
            "Quelle est la raison la plus mesquine pour laquelle tu as mis fin à une relation ?",
            "Pour quelle raison as-tu peur que les autres te jugent ?",
            "Quel est le compliment que tu préfères recevoir ?",
            "Qu'est-ce qui te fait dire « beurk » ?",
            "Quelle est la dernière chose que tu as recherchée sur Google ?",
            "Quel a été ton premier coup de cœur pour une personne célèbre ?",
            "Quelle est la chose la plus unique que tu aies jamais mangée ?",
            "Si tu devais participer à une émission de télé-réalité, laquelle serait-ce ?",
            "Quel a été ton pire premier rendez-vous ?",
            "À quelle tendance de mode embarrassante as-tu participé ?",
            "Quel est le film le plus embarrassant que tu considères comme l'un de tes préférés ?",
            "Quelle est la chanson la plus embarrassante qui était sur ton Spotify l'année dernière ?",
            "Quel est le pire cadeau que tu aies jamais reçu ?",
            "Quel est le meilleur conseil que tu aies jamais reçu ?",
            "Quand as-tu pleuré pour la dernière fois ?",
            "Si tu pouvais faire n'importe quel travail au monde, quel serait-il ?",
            "Si tu n'avais plus jamais à travailler, comment passerais-tu ton temps ?",
            "Quel est le plus grand secret que tu as caché à tes parents ?",
            "Quelle est la chose la plus illégale que tu aies jamais faite ?",
            "Quel a été ton dernier rêve ?",
            "Quel est ton souvenir d'enfance préféré ?",
            "30. Quel animal me ressemble le plus selon toi ?",
            "Lequel ou laquelle de mes ami.es est ton/ta préféré.e ?",
            "Quelle est ta plus grande peur concernant notre relation ?",
            "Est-ce que je t'ai déjà rendu jaloux.se ?",
            "Quelle a été ta première impression de moi ?",
            "Quel est ton souvenir préféré de nous deux ?",
            "Quelle est la chose que tu aimerais que nous fassions plus souvent ?",
            "Quelle est la chanson qui te fait penser à moi ?",
            "Quand as-tu su pour la première fois que tu étais amoureux.se de moi ?",
            "Quelle est la chose qui, selon toi, pourrait améliorer notre relation ?",
            "Qu’est-ce qui t'a attiré chez moi en premier ?",
            "Quelle scène de film aimerais-tu que nous recréions ?",
            "Quelle partie de mon corps préfères-tu ?",
            "Quelle chose t'excite le plus ?",
            "As-tu des fétiches que j'ignore ?",
            "À qui as-tu donné ton premier baiser ?",
            "Quand a eu lieu ta première fois ?",
            "Quand t'es-tu masturbé pour la dernière fois ?",
            "As-tu déjà trompé quelqu'un ?",
            "Quel est l'endroit le plus fou où tu as fait l'amour ?",
            "Quel vêtement de mon dressing trouves-tu le plus sexy ?",
            "Quel est l’acte sexuel que tu préfères recevoir ?",
            "Quel est l’acte sexuel que tu préfères offrir ?",
            "Quelle est ta position sexuelle préférée ?",
            "Quel sextoy voudrais-tu à tout prix essayer ?",
        ]
    },
    "shhhh": {
        "action": [
            "simule des cris d'orgasme sexuel à l'oreille de la personne à ta droite.",
            "Fais un bisou discret dans le cou à la personne de ton choix.",
            "Envoie un nude à ton crush actuel.",
            "embrasse une personne de maniere sensuelle.",
            "Frotte toi pendant 10 sec dans les parties erotiques (fesses,seins,sexe) d'une personne de sexe oppose.",
            "fais voir tes seins (torse).",
            "filme-toi en train de te masturber pendant 2 minutes devant tout le monde",
            "essaie d'exciter sexuellement une personne.",
            "fais voit ta chatte (theub).",
            "Laisse la personne à ta gauche te dessiner un petit cœur sur tes seins (torse)."
            "1. Retire le haut et montre-moi ton torse ou ta poitrine pendant 30 secondes,",
            "Enlève deux vêtements de ton choix dès maintenant,",
            "Fais un mini-défilé de mode sexy en sous-vêtements,",
            "Laisse-moi choisir le prochain vêtement que tu dois enlever,",
            "Déboutonne ma chemise ou mon haut en utilisant uniquement tes dents,",
            "Passe le reste du jeu uniquement en sous-vêtements,",
            "Montre-moi la marque de tes sous-vêtements",
            "Enlève tes chaussettes avec tes dents",
            "Prends la pose la plus sensuelle possible et laisse-moi t'admirer sans bouger pendant une minute,",
            "Retire un vêtement sans utiliser tes mains",
            "Laisse-moi déboutonner ou détacher ton sous-vêtement sans l'enlever,",
            "Fais un tour sur toi-même en dévoilant subtilement tes fesses,",
            "Mets un vêtement à l'envers, mais directement sur ta peau nue,",
            "Enlève ton bas et reste en culotte/caleçon pour les 3 prochains tours,",
            "Laisse-moi toucher ta poitrine ou ton torse sous tes vêtements pendant une minute,",
            "Choisis un de mes sous-vêtements et enfile-le devant moi,",
            "Déshabille-moi du regard en me décrivant exactement ce que tu aimerais m'enlever en premier,",
            "Reste figé(e) pendant que je retire lentement l'un de tes vêtements,",
            "Cache tes yeux et laisse-moi me déshabiller partiellement où je le souhaite,",
            "Enlève ton soutien-gorge ou ton haut sous ton t-shirt sans retirer ce dernier,",
            "Viens t'asseoir sur mes genoux à califourchon jusqu'au prochain tour,",
            "Embrasse-moi le long du cou jusqu'à la clavicule avec un maximum de sensualité,",
            "Fais couler un glaçon le long de mon torse ou de mon dos,",
            "Lèche une goutte de boisson ou de sirop directement sur ma peau,",
            "Caresse mes cuisses en remontant le plus haut possible sans toucher ma zone intime,",
            "Masse-moi les fesses pendant deux minutes entières,",
            "Colle ton corps tout nu contre le mien (si déjà déshabillé) pendant une minute,",
            "Embrasse mes lèvres en utilisant ta langue pour dessiner le contour de ma bouche avant d'approfondir,",
            "Caresse-toi là où tu aimes le plus pendant que je te regarde,",
            "Glisse tes mains sous mes sous-vêtements pour effleurer ma peau nue,",
            "Souffle doucement de l'air chaud sur mes zones les plus sensibles,",
            "Mordille délicatement le lobe de mon oreille en chuchotant ce que tu veux me faire,",
            "Allonge-toi sur moi et fais de légers mouvements de bassin contre le mien,",
            "Donne-moi trois fessées bien appliquées (avec l'intensité de mon choix),",
            "Laisse-moi masser tes zones érogènes préférées avec de l'huile ou de la crème,",
            "Trace une ligne avec ta langue partant de mon nombril et s'arrêtant juste au bord de mes sous-vêtements,",
            "Embrasse-moi à l'intérieur des cuisses,",
            "Reste les mains attachées ou croisées dans le dos pendant que je te caresse où je veux,",
            "Lèche mes doigts l'un après l'autre de manière très suggestive,",
            "Mets ma main exactement là où tu as envie que je te touche en ce moment,",
            "Fais-moi une démonstration de ce que tu sais faire avec tes mains sur mon corps,",
            "Mets-toi à quatre pattes et bouge ton bassin de façon rythmée et sexy,",
            "Essaye de m'exciter uniquement avec tes mots et ton souffle, sans me toucher,",
            "Enlève complètement tous tes vêtements et fais un strip-tease improvisé,",
            "Prends une position très osée et laisse-moi prendre une photo (qui restera strictement privée),",
            "Bande mes yeux et fais-moi deviner quelle partie de ton corps touche mon visage,",
            "Joue le rôle de mon professeur particulier très coquin pendant les deux prochains tours,",
            "Dis-moi quel est le scénario secret que tu as toujours voulu tester avec moi,",
            "Lèche mon cou tout en glissant une main dans mon entrejambe,",
            "Reste entièrement nu(e) devant moi pendant que je te pose trois questions indiscrètes,",
            "Fais mine de me soumettre en me bloquant les mains au-dessus de ma tête,",
            "Simule les bruits que tu fais quand nous sommes au lit pendant 30 secondes,",
            "Embrasse-moi partout, sauf sur la bouche et sur les zones génitales,",
            "Laisse-moi te caresser les seins ou le torse avec un glaçon,",
            "Mets-toi en sous-vêtements et va te regarder dans le miroir en me disant ce que tu trouves le plus sexy chez toi,",
            "Décris avec précision la dernière fois que tu as fantasmé sur moi,",
            "Guide ma bouche vers la partie de ton corps que tu veux que j'embrasse tout de suite,",
            "Reste assis(e) sur moi en frottant ton entrejambe contre le mien à travers les tissus,",
            "Enlève mes sous-vêtements en utilisant uniquement tes pieds,",
            "Dis-moi quel vêtement fétiche tu aimerais que j'achète pour notre prochaine fois,",
            "Retire ton tout dernier vêtement s'il te reste encore quelque chose,",
            "Donne-moi un avant-goût de préliminaires en utilisant ta bouche pendant deux minutes,",
            "Laisse-moi explorer ton intimité avec mes doigts pendant une chanson entière,",
            "Pratique une caresse buccale sur moi à travers mes sous-vêtements,",
            "Mets-toi dans ta position préférée pour faire l'amour et attends que je te rejoigne,",
            "Caresse-nous en même temps jusqu'à ce que l'un de nous n'en puisse plus,",
            "Utilisons un sextoy ensemble dès maintenant sur la zone de ton choix,",
            "Prends le contrôle total de la situation et déshabille-moi complètement,",
            "Embrasse-moi langoureusement pendant que tes mains s'activent dans mes sous-vêtements,",
            "Lèche ou embrasse mon corps en partant de mes pieds jusqu'à mon cou,",
            "Fais-moi jouir en utilisant uniquement tes mains,",
            "Choisis l'endroit de la pièce où tu veux qu'on fasse l'amour tout de suite,",
            "Laisse-moi te bander les yeux et te toucher là où je le décide sans que tu puisses réagir,",
            "Reste en position de soumission totale pendant que je m'occupe de ton plaisir,",
            "Murmure-moi ton désir le plus sauvage juste avant de m'embrasser avec passion,",
            "Enlève mes vêtements un par un avec une lenteur torturante,",
            "Fais monter l'excitation au maximum puis arrête-toi net pendant une minute pour me faire languir,",
            "Pratique un massage intégral du corps, fesses et cuisses incluses, en n'utilisant que ton torse nu,",
            "Laisse-moi te goûter là où c'est le plus chaud,",
            "Valide ce défi pour que nous arrêtions le jeu ici et passions directement aux choses sérieuses,",
        ],
        "verite": [
            "Quelle est la partie du corps que tu trouves la plus sexy chez les autres ?",
            "Quel est le rêve le plus fou ou osé que tu as fait récemment ?",
            "As-tu déjà eu un coup de cœur secret pour quelqu'un présent dans cette pièce ?",
            "Quel est ton plus grand fantasme inexploré ?",
            "Quelle est l'habitude la plus secrète ou bizarre que tu as quand tu es seul(e) ?",
            "Quel est l'endroit le plus insolite où tu as voulu avoir un moment intime ?",
            "Préfères-tu les lumières allumées ou complètement éteintes ?",
            "Quel est ton plus grand atout de séduction selon toi ?",
            "As-tu déjà envoyé un message coquin à la mauvaise personne ?",
            "Quel vêtement trouves-tu instantanément attirant chez quelqu'un ?"
        ]
    },
    "inavouable": {
        "action": [
            "Montre la dernière photo que tu as prise avec ton téléphone sans tricher.",
            "Imite la personne que tu aimes le moins dans cette pièce sans donner son nom.",
            "Laisse le groupe fouiller dans l'historique de recherche de ton navigateur.",
            "Raconte la blague la plus sombre ou déplacée que tu connaisses.",
            "Mime la pire honte de ta vie pour que le groupe la devine.",
            "Révèle le montant exact d'argent que tu as sur ton compte bancaire principal.",
            "Laisse quelqu'un lire tes trois derniers messages WhatsApp/SMS.",
            "Appelle un numéro au hasard et essaie de lui vendre un objet imaginaire pendant 1 minute.",
            "Raconte la pire rumeur que tu as lancée ou répétée sur quelqu'un.",
            "Montre au groupe l'application la plus honteuse installée sur ton téléphone."
        ],
        "verite": [
            "Quel est le plus gros mensonge que tu as dit à tes proches sans qu'ils le sachent ?",
            "As-Hu déjà fouillé en secret dans le téléphone de quelqu'un d'autre ?",
            "Quelle est la chose la plus illégale ou borderline que tu as faite ?",
            "As-tu déjà blâmé quelqu'un d'autre pour une bêtise commise par toi-même ?",
            "Quelle est l'opinion brute sur quelqu'un ici que tu as gardée secrète jusqu'à maintenant ?",
            "Qu'est-ce que tu as volé pour la dernière fois (même un stylo) ?",
            "Quel est le secret qu'on t'a confié et que tu as immédiatement répété ?",
            "As-tu déjà regretté amèrement d'être venu à une soirée ? Si oui, laquelle ?",
            "Quelle est la pire trahison amicale dont tu as été l'auteur ?",
            "Si tu devais supprimer une personne de ton entourage actuel pour toujours, ce serait qui ?"
        ]
    },
    "dilemme": {
        "action": [
            "Choisis : mange une cuillère de moutarde pure ou laisse le groupe poster un statut étrange sur tes réseaux.",
            "Choisis : donne ton téléphone déverrouillé à ton voisin pendant 2 minutes ou bois un grand verre d'eau d'un coup.",
            "Choisis : danse le tango avec un balai ou fais une déclaration solennelle à un mur.",
            "Choisis : imite un bébé qui pleure pendant 1 minute ou révèle ton pire complexe.",
            "Choisis : laisse quelqu'un te coiffer de manière ridicule ou chante l'hymne national à la fenêtre."
        ],
        "verite": [
            "Préfères-tu gagner 10 millions d'euros mais perdre tes souvenirs, ou rester pauvre et tout garder ?",
            "Préfères-tu pouvoir voler ou devenir invisible, sachant que l'autre option va à ton pire ennemi ?",
            "Si tu devais sauver une seule personne dans cette pièce d'un incendie, ce serait qui ?",
            "Préfères-tu connaître la date exacte de ta mort ou la cause de ta mort ?",
            "Préfères-tu passer un an sur une île déserte seul(e) ou un an en prison avec du monde ?",
            "Préfères-tu ne plus jamais pouvoir utiliser internet ou ne plus jamais pouvoir voyager ?",
            "Si tu devais épouser un personnage de fiction hideux mais richissime, tu le ferais ?",
            "Préfères-tu perdre l'usage de la parole ou devoir dire absolument tout ce que tu penses tout haut ?"
        ]
    },
    "brise-glace": {
        "action": [
            "Raconte une anecdote sur toi que personne absolument personne ici ne connaît.",
            "Fais une poignée de main secrète et ultra complexe avec ton voisin de gauche.",
            "Trouve un point commun improbable entre toi et la personne la plus éloignée de toi.",
            "Fais le tour complet de la pièce en marchant comme un robot des années 80.",
            "Fais une battle de compliments intenses de 30 secondes avec ton voisin de droite.",
            "Donne ta meilleure imitation d'une sirène de police ou de pompier.",
            "Raconte ton pire souvenir de premier jour d'école ou de travail.",
            "Fais deviner un film célèbre uniquement avec des bruits, sans aucun mot."
        ],
        "verite": [
            "Si ta vie était un film, quel en serait le titre et quel acteur jouerait ton rôle ?",
            "Quelle est la pire tendance mode ou musicale à laquelle tu as succombé par le passé ?",
            "Quelle est la toute première application que tu ouvres en te réveillant le matin ?",
            "Si tu pouvais voyager n'importe où dans le monde gratuitement demain, tu irais où ?",
            "Quel est le fait le plus bizarre ou inutile que tu connaisses par cœur ?",
            "Quel est le surnom le plus ridicule qu'on t'ait donné au cours de ta vie ?",
            "Quelle est la pire nourriture que tu as goûtée par politesse chez quelqu'un ?",
            "Si tu devais manger un seul aliment jusqu'à la fin de tes jours, ce serait quoi ?"
        ]
    }
}

class JeuConsumer(WebsocketConsumer):
    def connect(self):
        self.room_name = self.scope['url_route']['kwargs']['room_name']
        self.accept()

    def receive(self, text_data):
        data = json.loads(text_data)
        action_type = data.get('action')       # 'action' ou 'verite'
        categorie = data.get('categorie')     # 'amical', 'shhhh', etc.

        # Sécurisation des entrées
        if categorie not in BANQUE_QUESTIONS:
            categorie = "amical"
        if action_type not in ["action", "verite"]:
            action_type = "verite"

        # Sélection aléatoire sans répétition complexe
        liste_questions = BANQUE_QUESTIONS[categorie][action_type]
        question_choisie = random.choice(liste_questions)

        # Envoi au client
        self.send(text_data=json.dumps({
            'question': question_choisie
        }))